# ERROR MESSAGES

# Variables
VAR_REDEFINITION = 'RE-DEFINITION OF VARIABLE "{}"'
UNDEF_VAR = 'USE OF UNDEFINED VARIABLE "{}"'
MUST_DECLARE_VAR_TYPE = 'MUST DECLARE VARIABLE "{}" WITH TYPE (either implicitly via assignment or explicitly)'

# Expressions
TYPE_MISMATCH = 'Unsupported operand types for "{}" with "{}" and "{}"'
EXPECTED_BOOL = 'Expected boolean value but got "{}"'
VOID_FUNCTION_CALL_ON_EXPRESSION = 'CANNOT CALL VOID FUNCTION "{}" INSIDE EXPRESSION'

# Functions
FUNC_REDEFINITION = 'RE-DEFINITION OF FUNCTION "{}"'
UNDEF_FUNC = 'TRYING TO CALL UNDEFINED FUNCTION "{}"'
PARAM_AMOUNT_MISMATCH = 'TRYING TO CALL FUNCTION "{}" WITH INVALID AMOUNT OF PARAMS (correct is {})'
INVALID_SIGNATURE = 'INVALID FUNCTION SIGNATURE FOR "{}" \n\t\t\tgot: {}\n\t\t\twant: {}'
INVALID_RETURN_TYPE = 'CANNOT RETURN VALUE OF TYPE "{}" ON A FUNCTION THAT RETURNS "{}"'
RETURN_OUTSIDE_FUNC = 'CANNOT USE \'return\' STATEMENT OUTSIDE FUNCTION'
RETURN_ON_VOID_FUNC = 'CANNOT USE \'return\' ON VOID FUNCTION "{}"'
MUST_RETURN_ON_NON_VOID_FUNC = 'MUST HAVE AT LEAST ONE \'return\' ON NON-VOID FUNCTION "{}"'

# Loops
INVALID_BREAK_USE = 'CANNOT USE \'break\' STATEMENT OUTSIDE LOOP'

# Classes
CLASS_REDEFINITION = 'REDEFINITION OF CLASS "{}"'
UNDEF_CLASS = 'UNDEFINED CLASS {}'
UNDEF_PARENT = 'PARENT CLASS {} MUST BE DEFINED BEFORE CHILD CLASS {} '
UNDEF_METHOD = 'TRYING TO CALL UNDEFINED METHOD "{}" FROM CLASS "{}"'
NOT_PUBLIC_METHOD = 'TRYING TO ACCESS {} METHOD "{}" FROM CLASS "{}"'
UNDEF_ATTRIBUTE = 'TRYING TO CALL UNDEFINED ATTRIBUTE "{}" FROM CLASS "{}"'
NOT_PUBLIC_ATTRIBUTE = 'TRYING TO ACCESS {} ATTRIBUTE "{}" FROM CLASS "{}"'
INVALID_ATTRIBUTE_TYPE = 'CANNOT DECLARE AN ATTRIBUTE WITH CLASS TYPE'
MUST_DECLARE_ATTRIBUTE_TYPE = 'MUST DECLARE ATTRIBUTE "{}" WITH TYPE (either implicitly via assignment or explicitly)'
CLASS_ASSIGNMENT = 'CANNOT USE \'=\' OPERATOR WITH CLASSES'
SELF_USE_OUTSIDE_CLASS = 'CANNOT USE keyword \'self\' outside class context'

# Runtime Error
EXPECTED_TYPE = 'ERROR: Expected "{}" value but got "{}"'
CANNOT_CAST = 'ERROR: Cannot cast input "{}" to "{}"'