# ERROR MESSAGES

ERROR_PREFIX = 'ERROR!'

VAR_ALREADY_DEFINED = 'VAR {variable_id} ALREADY CREATED'
UNDEF_VAR = 'USE OF UNDEFINED VARIABLE "{}"'
TYPE_MISMATCHED = ''
ALREADY_DEFINED_ERROR = 'RE-DEFINITION OF {ID}'

# Function Errors
UNDEF_FUNC = 'TRYING TO CALL UNDEFINED FUNCTION "{}"'
PARAM_AMOUNT_MISMATCH = 'TRYING TO CALL FUNCTION "{}" WITH INVALID AMOUNT OF PARAMS (correct is {})'
INVALID_PARAM_TYPE = 'INVALID TYPE "{}" ON PARAMETER #{} WHEN CALLING FUNCTION "{}" (correct is {})'

# Class Errors
UNDEFINED_CLASS = 'UNDEFINED CLASS {class_name}'
PARENT_NOT_EXIST_ERROR = 'PARENT CLASS {parent_ID} MUST BE DEFINED BEFORE CHILD CLASS {child_ID} '
UNDEF_METHOD = 'TRYING TO CALL UNDEFINED METHOD "{}" FROM CLASS "{}"'
NOT_PUBLIC_METHOD = 'TRYING TO ACCESS {} METHOD "{}" FROM CLASS "{}"'
UNDEF_ATTRIBUTE = 'TRYING TO CALL UNDEFINED ATTRIBUTE "{}" FROM CLASS "{}"'
NOT_PUBLIC_ATTRIBUTE = 'TRYING TO ACCESS {} ATTRIBUTE "{}" FROM CLASS "{}"'
