# ERROR MESSAGES

ERROR_PREFIX = 'ERROR!'

VAR_ALREADY_DEFINED = 'VAR {variable_id} ALREADY CREATED'
TYPE_MISMATCHED = ''
UNDEFINED_CLASS = 'UNDEFINED CLASS {class_name}'
ALREADY_DEFINED_ERROR = 'RE-DEFINITION OF {ID}'
PARENT_NOT_EXIST_ERROR = 'PARENT CLASS {parent_ID} MUST BE DEFINED BEFORE CHILD CLASS {child_ID} '
