# OPERATORS
ADDITION = 1
SUBSTRACTION = 2
MULTIPLICATION = 3
DIVISION = 4
POWER = 5
MODULO = 6
ASSIGN = 7
PLUSASSIGN = 8
SUBSASSIGN = 9
MULTASSIGN = 10
DIVIDEASSIGN = 11
MODULOASSIGN = 12

# CONDITIONAL OPERATORS
LESSERTHAN = 13
GREATERTHAN = 14
LESSEROREQUAL = 15
GREATEROREQUAL = 16
ISOPERATOR = 17
ANDOPERATOR = 18
OROPERATOR = 19
NOTOPERATOR = 20
